### ISSUE TITLE
index 建设

### ISSUE THREAD

**Issue by Master-Hash** [Master-Hash/postcard-legacy#3]
@Xecades 现在的主页只是占位置用的……希望有一个像样子的主页，
其中需要包含一张演示图，Github 链接和我的主页，还有简要的用法说明。

前端的工作也交给你了（

**Comment by Xecades** [comment]
> @Xecades 现在的主页只是占位置用的……希望有一个像样子的主页，
> 其中需要包含一张演示图，Github 链接和我的主页，还有简要的用法说明。
> 
> 前端的工作也交给你了（

“主页” 是什么？

**Comment by Master-Hash** [comment]
采用了 Xecades 过去的方案，直接 301 到 GitHub 项目主页。
前段不是我的专长，建设之类的，还是算了。
